// auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = " LOGOUT_SUCCESS";
export const LOGOUT_FAIL = " LOGOUT_FAIL";
export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
export const SET_SECURITY_PIN = "SET_SECURITY_PIN";
export const SET_SECURITY_PIN_FAIL = "SET_SECURITY_PIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_SUCCESS_MESSAGE = "CLEAR_SUCCESS_MESSAGE";
// movies
export const FETCH_TRENDING_MOVIES = "FETCH_TRENDING_MOVIES";
export const FETCH_TRENDING_MOVIES_FAIL = "FETCH_TRENDING_MOVIES_FAIL";
export const FETCH_SAVED_MOVIES = "FETCH_SAVED_MOVIES";
export const FETCH_SAVED_MOVIES_FAIL = "FETCH_SAVED_MOVIES_FAIL";
export const SAVE_MOVIE = "SAVE_MOVIE";
export const SAVE_MOVIE_FAIL = "SAVE_MOVIE_FAIL";
// user profile
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";
export const TOGGLE_MULTI_PROFILE = "TOGGLE_MULTI_PROFILE";
export const TOGGLE_MULTI_PROFILE_FAIL = "TOGGLE_MULTI_PROFILE_FAIL";
export const SET_CURRENT_PROFILE_SUCCESS = "SET_CURRENT_PROFILE_SUCCESS";
export const SET_CURRENT_PROFILE_FAIL = "SET_CURRENT_PROFILE_FAIL";

export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAIL = "CREATE_PROFILE_FAIL";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL";







// user details
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAIL = "FETCH_USER_DETAILS_FAIL";
// email verification
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAIL = "VERIFY_EMAIL_FAIL";
// password reset
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";